name: Full Stack CI

on:
  pull_request:
    branches: [main]

jobs:
  ci-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Install PM2 globally
        run: npm install --global pm2

      - name: Backend smoke test
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CLIENT_ORIGIN: ${{ secrets.CLIENT_ORIGIN }}
          PORT: 4000
        run: |
          set -euo pipefail
          export CLIENT_ORIGIN=${CLIENT_ORIGIN:-http://localhost:5173}
          export JWT_SECRET=${JWT_SECRET:-test-secret}
          export PORT=${PORT:-4000}

          pm2 delete backend >/dev/null 2>&1 || true
          pm2 start src/server.js --name backend --update-env

          ready=false
          for attempt in {1..10}; do
            if curl --fail --silent http://localhost:${PORT}/ >/dev/null; then
              ready=true
              break
            fi
            sleep 2
          done

          if [ "$ready" = false ]; then
            pm2 logs backend --lines 100 || true
            echo "Backend did not become ready" >&2
            exit 1
          fi

          echo "Backend responded successfully"

      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: frontend
        env:
          PLAYWRIGHT_BASE_URL: http://127.0.0.1:4173
        run: npm run test

      - name: Stop backend
        if: always()
        run: pm2 delete backend >/dev/null 2>&1 || true
